import type { LanguageCode } from './i18n';

export type AuthFlowCopy = {
  debugCode: string;
  enterNewPassword: string;
  enterPhoneFirst: string;
  enterVerificationCode: string;
  newPassword: string;
  optionalPhoneNumber: string;
  passwordRecoveryRequestFailed: string;
  passwordResetFailed: string;
  passwordResetSuccessful: string;
  phone: string;
  phoneNumber: string;
  recoveryCodeSent: string;
  requestPasswordRecovery: string;
  requestingCode: string;
  resendVerificationCode: string;
  resetPassword: string;
  resetting: string;
  returnToSignIn: string;
  sendVerificationCodeFailed: string;
  verificationCode: string;
};

const AUTH_FLOW_COPY_BY_LANGUAGE = {
  'af-ZA': {
    debugCode: 'Ontfoutkode',
    enterNewPassword: 'Voer ’n nuwe wagwoord in',
    enterPhoneFirst: 'Voer eers ’n telefoonnommer in',
    enterVerificationCode: 'Voer verifikasiekode in',
    newPassword: 'Nuwe wagwoord',
    optionalPhoneNumber: 'Telefoonnommer (opsioneel)',
    passwordRecoveryRequestFailed: 'Wagwoordherstelversoek het misluk',
    passwordResetFailed: 'Wagwoordherstel het misluk',
    passwordResetSuccessful: 'Wagwoord is herstel. Jy kan nou met die nuwe wagwoord aanmeld.',
    phone: 'Telefoon',
    phoneNumber: 'Telefoonnommer',
    recoveryCodeSent: 'As hierdie nommer bestaan, is ’n verifikasiekode gestuur.',
    requestPasswordRecovery: 'Versoek wagwoordherstel',
    requestingCode: 'Kode word versoek...',
    resendVerificationCode: 'Stuur verifikasiekode weer',
    resetPassword: 'Herstel wagwoord',
    resetting: 'Herstel...',
    returnToSignIn: 'Terug na aanmelding',
    sendVerificationCodeFailed: 'Kon nie verifikasiekode stuur nie',
    verificationCode: 'Verifikasiekode'
  },
  'am-ET': {
    debugCode: 'የማረሚያ ኮድ',
    enterNewPassword: 'አዲስ የይለፍ ቃል ያስገቡ',
    enterPhoneFirst: 'መጀመሪያ ስልክ ቁጥር ያስገቡ',
    enterVerificationCode: 'የማረጋገጫ ኮድ ያስገቡ',
    newPassword: 'አዲስ የይለፍ ቃል',
    optionalPhoneNumber: 'ስልክ ቁጥር (አማራጭ)',
    passwordRecoveryRequestFailed: 'የይለፍ ቃል መልሶ ማግኛ ጥያቄ አልተሳካም',
    passwordResetFailed: 'የይለፍ ቃል ዳግም ማስጀመር አልተሳካም',
    passwordResetSuccessful: 'የይለፍ ቃል ተቀይሯል። አሁን በአዲሱ የይለፍ ቃል መግባት ይችላሉ።',
    phone: 'ስልክ',
    phoneNumber: 'ስልክ ቁጥር',
    recoveryCodeSent: 'ቁጥሩ ካለ የማረጋገጫ ኮድ ተልኳል።',
    requestPasswordRecovery: 'የይለፍ ቃል መልሶ ማግኛ ጠይቅ',
    requestingCode: 'ኮድ በመጠየቅ ላይ...',
    resendVerificationCode: 'የማረጋገጫ ኮድ እንደገና ላክ',
    resetPassword: 'የይለፍ ቃል ዳግም አስጀምር',
    resetting: 'በመቀየር ላይ...',
    returnToSignIn: 'ወደ መግቢያ ተመለስ',
    sendVerificationCodeFailed: 'የማረጋገጫ ኮድ መላክ አልተሳካም',
    verificationCode: 'የማረጋገጫ ኮድ'
  },
  'ar-EG': {
    debugCode: 'رمز التصحيح',
    enterNewPassword: 'أدخل كلمة مرور جديدة',
    enterPhoneFirst: 'أدخل رقم الهاتف أولاً',
    enterVerificationCode: 'أدخل رمز التحقق',
    newPassword: 'كلمة مرور جديدة',
    optionalPhoneNumber: 'رقم الهاتف (اختياري)',
    passwordRecoveryRequestFailed: 'فشل طلب استرداد كلمة المرور',
    passwordResetFailed: 'فشل إعادة تعيين كلمة المرور',
    passwordResetSuccessful: 'تمت إعادة تعيين كلمة المرور. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    phone: 'الهاتف',
    phoneNumber: 'رقم الهاتف',
    recoveryCodeSent: 'إذا كان الرقم موجوداً، فقد تم إرسال رمز تحقق.',
    requestPasswordRecovery: 'طلب استرداد كلمة المرور',
    requestingCode: 'جارٍ طلب الرمز...',
    resendVerificationCode: 'إعادة إرسال رمز التحقق',
    resetPassword: 'إعادة تعيين كلمة المرور',
    resetting: 'جارٍ إعادة التعيين...',
    returnToSignIn: 'العودة إلى تسجيل الدخول',
    sendVerificationCodeFailed: 'فشل إرسال رمز التحقق',
    verificationCode: 'رمز التحقق'
  },
  'de-DE': {
    debugCode: 'Debug-Code',
    enterNewPassword: 'Neues Passwort eingeben',
    enterPhoneFirst: 'Bitte zuerst eine Telefonnummer eingeben',
    enterVerificationCode: 'Bestätigungscode eingeben',
    newPassword: 'Neues Passwort',
    optionalPhoneNumber: 'Telefonnummer (optional)',
    passwordRecoveryRequestFailed: 'Passwort-Wiederherstellung fehlgeschlagen',
    passwordResetFailed: 'Passwort konnte nicht zurückgesetzt werden',
    passwordResetSuccessful: 'Das Passwort wurde zurückgesetzt. Sie können sich jetzt mit dem neuen Passwort anmelden.',
    phone: 'Telefon',
    phoneNumber: 'Telefonnummer',
    recoveryCodeSent: 'Wenn diese Nummer existiert, wurde ein Bestätigungscode gesendet.',
    requestPasswordRecovery: 'Passwort-Wiederherstellung anfordern',
    requestingCode: 'Code wird angefordert...',
    resendVerificationCode: 'Bestätigungscode erneut senden',
    resetPassword: 'Passwort zurücksetzen',
    resetting: 'Wird zurückgesetzt...',
    returnToSignIn: 'Zurück zur Anmeldung',
    sendVerificationCodeFailed: 'Bestätigungscode konnte nicht gesendet werden',
    verificationCode: 'Bestätigungscode'
  },
  'en-US': {
    debugCode: 'Debug code',
    enterNewPassword: 'Enter a new password',
    enterPhoneFirst: 'Enter a phone number first',
    enterVerificationCode: 'Enter verification code',
    newPassword: 'New password',
    optionalPhoneNumber: 'Phone number (optional)',
    passwordRecoveryRequestFailed: 'Password recovery request failed',
    passwordResetFailed: 'Password reset failed',
    passwordResetSuccessful: 'Password reset successful. You can now log in with your new password.',
    phone: 'Phone',
    phoneNumber: 'Phone number',
    recoveryCodeSent: 'If the number exists, a verification code has been sent.',
    requestPasswordRecovery: 'Request password recovery',
    requestingCode: 'Requesting code...',
    resendVerificationCode: 'Resend verification code',
    resetPassword: 'Reset password',
    resetting: 'Resetting...',
    returnToSignIn: 'Return to sign in',
    sendVerificationCodeFailed: 'Failed to send verification code',
    verificationCode: 'Verification code'
  },
  'es-ES': {
    debugCode: 'Código de depuración',
    enterNewPassword: 'Introduce una contraseña nueva',
    enterPhoneFirst: 'Introduce primero un número de teléfono',
    enterVerificationCode: 'Introduce el código de verificación',
    newPassword: 'Contraseña nueva',
    optionalPhoneNumber: 'Número de teléfono (opcional)',
    passwordRecoveryRequestFailed: 'No se pudo solicitar la recuperación de contraseña',
    passwordResetFailed: 'No se pudo restablecer la contraseña',
    passwordResetSuccessful: 'Contraseña restablecida. Ya puedes iniciar sesión con la nueva contraseña.',
    phone: 'Teléfono',
    phoneNumber: 'Número de teléfono',
    recoveryCodeSent: 'Si el número existe, se ha enviado un código de verificación.',
    requestPasswordRecovery: 'Solicitar recuperación de contraseña',
    requestingCode: 'Solicitando código...',
    resendVerificationCode: 'Reenviar código de verificación',
    resetPassword: 'Restablecer contraseña',
    resetting: 'Restableciendo...',
    returnToSignIn: 'Volver al inicio de sesión',
    sendVerificationCodeFailed: 'No se pudo enviar el código de verificación',
    verificationCode: 'Código de verificación'
  },
  'fa-IR': {
    debugCode: 'کد اشکال‌زدایی',
    enterNewPassword: 'رمز عبور جدید را وارد کنید',
    enterPhoneFirst: 'ابتدا شماره تلفن را وارد کنید',
    enterVerificationCode: 'کد تأیید را وارد کنید',
    newPassword: 'رمز عبور جدید',
    optionalPhoneNumber: 'شماره تلفن (اختیاری)',
    passwordRecoveryRequestFailed: 'درخواست بازیابی رمز عبور ناموفق بود',
    passwordResetFailed: 'بازنشانی رمز عبور ناموفق بود',
    passwordResetSuccessful: 'رمز عبور بازنشانی شد. اکنون می‌توانید با رمز جدید وارد شوید.',
    phone: 'تلفن',
    phoneNumber: 'شماره تلفن',
    recoveryCodeSent: 'اگر این شماره وجود داشته باشد، کد تأیید ارسال شده است.',
    requestPasswordRecovery: 'درخواست بازیابی رمز عبور',
    requestingCode: 'در حال درخواست کد...',
    resendVerificationCode: 'ارسال دوباره کد تأیید',
    resetPassword: 'بازنشانی رمز عبور',
    resetting: 'در حال بازنشانی...',
    returnToSignIn: 'بازگشت به ورود',
    sendVerificationCodeFailed: 'ارسال کد تأیید ناموفق بود',
    verificationCode: 'کد تأیید'
  },
  'fr-FR': {
    debugCode: 'Code de débogage',
    enterNewPassword: 'Saisissez un nouveau mot de passe',
    enterPhoneFirst: 'Saisissez d’abord un numéro de téléphone',
    enterVerificationCode: 'Saisissez le code de vérification',
    newPassword: 'Nouveau mot de passe',
    optionalPhoneNumber: 'Numéro de téléphone (facultatif)',
    passwordRecoveryRequestFailed: 'La demande de récupération a échoué',
    passwordResetFailed: 'La réinitialisation du mot de passe a échoué',
    passwordResetSuccessful: 'Mot de passe réinitialisé. Vous pouvez maintenant vous connecter avec le nouveau mot de passe.',
    phone: 'Téléphone',
    phoneNumber: 'Numéro de téléphone',
    recoveryCodeSent: 'Si ce numéro existe, un code de vérification a été envoyé.',
    requestPasswordRecovery: 'Demander la récupération du mot de passe',
    requestingCode: 'Demande du code...',
    resendVerificationCode: 'Renvoyer le code de vérification',
    resetPassword: 'Réinitialiser le mot de passe',
    resetting: 'Réinitialisation...',
    returnToSignIn: 'Retour à la connexion',
    sendVerificationCodeFailed: 'Impossible d’envoyer le code de vérification',
    verificationCode: 'Code de vérification'
  },
  'ha-NG': {
    debugCode: 'Lambar gyara',
    enterNewPassword: 'Shigar da sabon kalmar sirri',
    enterPhoneFirst: 'Da farko shigar da lambar waya',
    enterVerificationCode: 'Shigar da lambar tabbatarwa',
    newPassword: 'Sabuwar kalmar sirri',
    optionalPhoneNumber: 'Lambar waya (na zaɓi)',
    passwordRecoveryRequestFailed: 'Neman dawo da kalmar sirri ya kasa',
    passwordResetFailed: 'Sake saita kalmar sirri ya kasa',
    passwordResetSuccessful: 'An sake saita kalmar sirri. Yanzu zaka iya shiga da sabuwar kalmar sirri.',
    phone: 'Waya',
    phoneNumber: 'Lambar waya',
    recoveryCodeSent: 'Idan lambar tana nan, an aika lambar tabbatarwa.',
    requestPasswordRecovery: 'Nemi dawo da kalmar sirri',
    requestingCode: 'Ana neman lamba...',
    resendVerificationCode: 'Sake aika lambar tabbatarwa',
    resetPassword: 'Sake saita kalmar sirri',
    resetting: 'Ana sake saitawa...',
    returnToSignIn: 'Koma shiga',
    sendVerificationCodeFailed: 'Aika lambar tabbatarwa ya kasa',
    verificationCode: 'Lambar tabbatarwa'
  },
  'hi-IN': {
    debugCode: 'डिबग कोड',
    enterNewPassword: 'नया पासवर्ड दर्ज करें',
    enterPhoneFirst: 'पहले फोन नंबर दर्ज करें',
    enterVerificationCode: 'सत्यापन कोड दर्ज करें',
    newPassword: 'नया पासवर्ड',
    optionalPhoneNumber: 'फोन नंबर (वैकल्पिक)',
    passwordRecoveryRequestFailed: 'पासवर्ड रिकवरी अनुरोध विफल',
    passwordResetFailed: 'पासवर्ड रीसेट विफल',
    passwordResetSuccessful: 'पासवर्ड रीसेट हो गया। अब आप नए पासवर्ड से लॉगिन कर सकते हैं।',
    phone: 'फोन',
    phoneNumber: 'फोन नंबर',
    recoveryCodeSent: 'यदि यह नंबर मौजूद है, तो सत्यापन कोड भेजा गया है।',
    requestPasswordRecovery: 'पासवर्ड रिकवरी का अनुरोध करें',
    requestingCode: 'कोड मांगा जा रहा है...',
    resendVerificationCode: 'सत्यापन कोड फिर से भेजें',
    resetPassword: 'पासवर्ड रीसेट करें',
    resetting: 'रीसेट हो रहा है...',
    returnToSignIn: 'लॉगिन पर लौटें',
    sendVerificationCodeFailed: 'सत्यापन कोड भेजने में विफल',
    verificationCode: 'सत्यापन कोड'
  },
  'id-ID': {
    debugCode: 'Kode debug',
    enterNewPassword: 'Masukkan kata sandi baru',
    enterPhoneFirst: 'Masukkan nomor telepon terlebih dahulu',
    enterVerificationCode: 'Masukkan kode verifikasi',
    newPassword: 'Kata sandi baru',
    optionalPhoneNumber: 'Nomor telepon (opsional)',
    passwordRecoveryRequestFailed: 'Permintaan pemulihan kata sandi gagal',
    passwordResetFailed: 'Reset kata sandi gagal',
    passwordResetSuccessful: 'Kata sandi berhasil direset. Anda sekarang dapat masuk dengan kata sandi baru.',
    phone: 'Telepon',
    phoneNumber: 'Nomor telepon',
    recoveryCodeSent: 'Jika nomor tersebut ada, kode verifikasi telah dikirim.',
    requestPasswordRecovery: 'Minta pemulihan kata sandi',
    requestingCode: 'Meminta kode...',
    resendVerificationCode: 'Kirim ulang kode verifikasi',
    resetPassword: 'Reset kata sandi',
    resetting: 'Mereset...',
    returnToSignIn: 'Kembali masuk',
    sendVerificationCodeFailed: 'Gagal mengirim kode verifikasi',
    verificationCode: 'Kode verifikasi'
  },
  'ig-NG': {
    debugCode: 'Koodu ndozi',
    enterNewPassword: 'Tinye okwuntughe ọhụrụ',
    enterPhoneFirst: 'Tinye nọmba ekwentị mbụ',
    enterVerificationCode: 'Tinye koodu nkwenye',
    newPassword: 'Okwuntughe ọhụrụ',
    optionalPhoneNumber: 'Nọmba ekwentị (nhọrọ)',
    passwordRecoveryRequestFailed: 'Arịrịọ mgbake okwuntughe dara',
    passwordResetFailed: 'Ịtọgharịa okwuntughe dara',
    passwordResetSuccessful: 'A tọgharịrị okwuntughe. Ị nwere ike iji okwuntughe ọhụrụ banye ugbu a.',
    phone: 'Ekwentị',
    phoneNumber: 'Nọmba ekwentị',
    recoveryCodeSent: 'Ọ bụrụ na nọmba a dị, ezipụla koodu nkwenye.',
    requestPasswordRecovery: 'Rịọ mgbake okwuntughe',
    requestingCode: 'Na-arịọ koodu...',
    resendVerificationCode: 'Zipụgharịa koodu nkwenye',
    resetPassword: 'Tọgharịa okwuntughe',
    resetting: 'Na-atọgharịa...',
    returnToSignIn: 'Laghachi nbanye',
    sendVerificationCodeFailed: 'Izipu koodu nkwenye dara',
    verificationCode: 'Koodu nkwenye'
  },
  'it-IT': {
    debugCode: 'Codice di debug',
    enterNewPassword: 'Inserisci una nuova password',
    enterPhoneFirst: 'Inserisci prima un numero di telefono',
    enterVerificationCode: 'Inserisci il codice di verifica',
    newPassword: 'Nuova password',
    optionalPhoneNumber: 'Numero di telefono (opzionale)',
    passwordRecoveryRequestFailed: 'Richiesta di recupero password non riuscita',
    passwordResetFailed: 'Reimpostazione password non riuscita',
    passwordResetSuccessful: 'Password reimpostata. Ora puoi accedere con la nuova password.',
    phone: 'Telefono',
    phoneNumber: 'Numero di telefono',
    recoveryCodeSent: 'Se il numero esiste, è stato inviato un codice di verifica.',
    requestPasswordRecovery: 'Richiedi recupero password',
    requestingCode: 'Richiesta codice...',
    resendVerificationCode: 'Reinvia codice di verifica',
    resetPassword: 'Reimposta password',
    resetting: 'Reimpostazione...',
    returnToSignIn: 'Torna all’accesso',
    sendVerificationCodeFailed: 'Invio del codice di verifica non riuscito',
    verificationCode: 'Codice di verifica'
  },
  'ja-JP': {
    debugCode: 'デバッグコード',
    enterNewPassword: '新しいパスワードを入力してください',
    enterPhoneFirst: '先に電話番号を入力してください',
    enterVerificationCode: '確認コードを入力してください',
    newPassword: '新しいパスワード',
    optionalPhoneNumber: '電話番号（任意）',
    passwordRecoveryRequestFailed: 'パスワード再設定の申請に失敗しました',
    passwordResetFailed: 'パスワードの再設定に失敗しました',
    passwordResetSuccessful: 'パスワードを再設定しました。新しいパスワードでログインできます。',
    phone: '電話',
    phoneNumber: '電話番号',
    recoveryCodeSent: 'この番号が存在する場合、確認コードを送信しました。',
    requestPasswordRecovery: 'パスワード再設定を申請',
    requestingCode: 'コードを申請中...',
    resendVerificationCode: '確認コードを再送信',
    resetPassword: 'パスワードを再設定',
    resetting: '再設定中...',
    returnToSignIn: 'ログインに戻る',
    sendVerificationCodeFailed: '確認コードの送信に失敗しました',
    verificationCode: '確認コード'
  },
  'ko-KR': {
    debugCode: '디버그 코드',
    enterNewPassword: '새 비밀번호를 입력하세요',
    enterPhoneFirst: '먼저 전화번호를 입력하세요',
    enterVerificationCode: '인증 코드를 입력하세요',
    newPassword: '새 비밀번호',
    optionalPhoneNumber: '전화번호 (선택)',
    passwordRecoveryRequestFailed: '비밀번호 복구 요청에 실패했습니다',
    passwordResetFailed: '비밀번호 재설정에 실패했습니다',
    passwordResetSuccessful: '비밀번호가 재설정되었습니다. 새 비밀번호로 로그인할 수 있습니다.',
    phone: '전화',
    phoneNumber: '전화번호',
    recoveryCodeSent: '해당 번호가 있으면 인증 코드가 전송되었습니다.',
    requestPasswordRecovery: '비밀번호 복구 요청',
    requestingCode: '코드 요청 중...',
    resendVerificationCode: '인증 코드 다시 보내기',
    resetPassword: '비밀번호 재설정',
    resetting: '재설정 중...',
    returnToSignIn: '로그인으로 돌아가기',
    sendVerificationCodeFailed: '인증 코드 전송 실패',
    verificationCode: '인증 코드'
  },
  'ms-MY': {
    debugCode: 'Kod nyahpepijat',
    enterNewPassword: 'Masukkan kata laluan baharu',
    enterPhoneFirst: 'Masukkan nombor telefon dahulu',
    enterVerificationCode: 'Masukkan kod pengesahan',
    newPassword: 'Kata laluan baharu',
    optionalPhoneNumber: 'Nombor telefon (pilihan)',
    passwordRecoveryRequestFailed: 'Permintaan pemulihan kata laluan gagal',
    passwordResetFailed: 'Tetapan semula kata laluan gagal',
    passwordResetSuccessful: 'Kata laluan berjaya ditetapkan semula. Anda kini boleh log masuk dengan kata laluan baharu.',
    phone: 'Telefon',
    phoneNumber: 'Nombor telefon',
    recoveryCodeSent: 'Jika nombor itu wujud, kod pengesahan telah dihantar.',
    requestPasswordRecovery: 'Minta pemulihan kata laluan',
    requestingCode: 'Meminta kod...',
    resendVerificationCode: 'Hantar semula kod pengesahan',
    resetPassword: 'Tetapkan semula kata laluan',
    resetting: 'Menetapkan semula...',
    returnToSignIn: 'Kembali ke log masuk',
    sendVerificationCodeFailed: 'Gagal menghantar kod pengesahan',
    verificationCode: 'Kod pengesahan'
  },
  'nl-NL': {
    debugCode: 'Debugcode',
    enterNewPassword: 'Voer een nieuw wachtwoord in',
    enterPhoneFirst: 'Voer eerst een telefoonnummer in',
    enterVerificationCode: 'Voer verificatiecode in',
    newPassword: 'Nieuw wachtwoord',
    optionalPhoneNumber: 'Telefoonnummer (optioneel)',
    passwordRecoveryRequestFailed: 'Aanvraag voor wachtwoordherstel mislukt',
    passwordResetFailed: 'Wachtwoord resetten mislukt',
    passwordResetSuccessful: 'Wachtwoord opnieuw ingesteld. Je kunt nu inloggen met het nieuwe wachtwoord.',
    phone: 'Telefoon',
    phoneNumber: 'Telefoonnummer',
    recoveryCodeSent: 'Als dit nummer bestaat, is er een verificatiecode verzonden.',
    requestPasswordRecovery: 'Wachtwoordherstel aanvragen',
    requestingCode: 'Code aanvragen...',
    resendVerificationCode: 'Verificatiecode opnieuw verzenden',
    resetPassword: 'Wachtwoord resetten',
    resetting: 'Resetten...',
    returnToSignIn: 'Terug naar inloggen',
    sendVerificationCodeFailed: 'Verificatiecode verzenden mislukt',
    verificationCode: 'Verificatiecode'
  },
  'om-ET': {
    debugCode: 'Koodii sirreessaa',
    enterNewPassword: 'Jecha darbii haaraa galchi',
    enterPhoneFirst: 'Dura lakkoofsa bilbilaa galchi',
    enterVerificationCode: 'Koodii mirkaneessaa galchi',
    newPassword: 'Jecha darbii haaraa',
    optionalPhoneNumber: 'Lakkoofsa bilbilaa (filannoo)',
    passwordRecoveryRequestFailed: 'Gaaffiin deebisuu jecha darbii hin milkoofne',
    passwordResetFailed: 'Jecha darbii haaromsuun hin milkoofne',
    passwordResetSuccessful: 'Jecha darbii haaromfameera. Amma jecha darbii haaraadhaan seenuu dandeessa.',
    phone: 'Bilbila',
    phoneNumber: 'Lakkoofsa bilbilaa',
    recoveryCodeSent: 'Yoo lakkoofsi jiraate, koodiin mirkaneessaa ergameera.',
    requestPasswordRecovery: 'Deebisuu jecha darbii gaafadhu',
    requestingCode: 'Koodii gaafachaa jira...',
    resendVerificationCode: 'Koodii mirkaneessaa irra deebi’i ergi',
    resetPassword: 'Jecha darbii haaromsi',
    resetting: 'Haaromsaa jira...',
    returnToSignIn: 'Gara seenuutti deebi’i',
    sendVerificationCodeFailed: 'Koodii mirkaneessaa erguun hin milkoofne',
    verificationCode: 'Koodii mirkaneessaa'
  },
  'pl-PL': {
    debugCode: 'Kod debugowania',
    enterNewPassword: 'Wprowadź nowe hasło',
    enterPhoneFirst: 'Najpierw wprowadź numer telefonu',
    enterVerificationCode: 'Wprowadź kod weryfikacyjny',
    newPassword: 'Nowe hasło',
    optionalPhoneNumber: 'Numer telefonu (opcjonalnie)',
    passwordRecoveryRequestFailed: 'Nie udało się wysłać prośby o odzyskanie hasła',
    passwordResetFailed: 'Reset hasła nie powiódł się',
    passwordResetSuccessful: 'Hasło zostało zresetowane. Możesz teraz zalogować się nowym hasłem.',
    phone: 'Telefon',
    phoneNumber: 'Numer telefonu',
    recoveryCodeSent: 'Jeśli numer istnieje, wysłano kod weryfikacyjny.',
    requestPasswordRecovery: 'Poproś o odzyskanie hasła',
    requestingCode: 'Wysyłanie kodu...',
    resendVerificationCode: 'Wyślij kod weryfikacyjny ponownie',
    resetPassword: 'Zresetuj hasło',
    resetting: 'Resetowanie...',
    returnToSignIn: 'Wróć do logowania',
    sendVerificationCodeFailed: 'Nie udało się wysłać kodu weryfikacyjnego',
    verificationCode: 'Kod weryfikacyjny'
  },
  'pt-BR': {
    debugCode: 'Código de depuração',
    enterNewPassword: 'Digite uma nova senha',
    enterPhoneFirst: 'Digite primeiro um número de telefone',
    enterVerificationCode: 'Digite o código de verificação',
    newPassword: 'Nova senha',
    optionalPhoneNumber: 'Número de telefone (opcional)',
    passwordRecoveryRequestFailed: 'Falha ao solicitar recuperação de senha',
    passwordResetFailed: 'Falha ao redefinir a senha',
    passwordResetSuccessful: 'Senha redefinida. Agora você pode entrar com a nova senha.',
    phone: 'Telefone',
    phoneNumber: 'Número de telefone',
    recoveryCodeSent: 'Se o número existir, um código de verificação foi enviado.',
    requestPasswordRecovery: 'Solicitar recuperação de senha',
    requestingCode: 'Solicitando código...',
    resendVerificationCode: 'Reenviar código de verificação',
    resetPassword: 'Redefinir senha',
    resetting: 'Redefinindo...',
    returnToSignIn: 'Voltar ao login',
    sendVerificationCodeFailed: 'Falha ao enviar código de verificação',
    verificationCode: 'Código de verificação'
  },
  'ru-RU': {
    debugCode: 'Отладочный код',
    enterNewPassword: 'Введите новый пароль',
    enterPhoneFirst: 'Сначала введите номер телефона',
    enterVerificationCode: 'Введите код подтверждения',
    newPassword: 'Новый пароль',
    optionalPhoneNumber: 'Номер телефона (необязательно)',
    passwordRecoveryRequestFailed: 'Не удалось запросить восстановление пароля',
    passwordResetFailed: 'Не удалось сбросить пароль',
    passwordResetSuccessful: 'Пароль сброшен. Теперь вы можете войти с новым паролем.',
    phone: 'Телефон',
    phoneNumber: 'Номер телефона',
    recoveryCodeSent: 'Если номер существует, код подтверждения отправлен.',
    requestPasswordRecovery: 'Запросить восстановление пароля',
    requestingCode: 'Запрос кода...',
    resendVerificationCode: 'Отправить код повторно',
    resetPassword: 'Сбросить пароль',
    resetting: 'Сброс...',
    returnToSignIn: 'Вернуться ко входу',
    sendVerificationCodeFailed: 'Не удалось отправить код подтверждения',
    verificationCode: 'Код подтверждения'
  },
  'rw-RW': {
    debugCode: 'Kode yo gusuzuma',
    enterNewPassword: 'Andika ijambo ry’ibanga rishya',
    enterPhoneFirst: 'Banza wandike nimero ya telefoni',
    enterVerificationCode: 'Andika kode yo kwemeza',
    newPassword: 'Ijambo ry’ibanga rishya',
    optionalPhoneNumber: 'Nimero ya telefoni (si ngombwa)',
    passwordRecoveryRequestFailed: 'Gusaba kugarura ijambo ry’ibanga byanze',
    passwordResetFailed: 'Gusubizaho ijambo ry’ibanga byanze',
    passwordResetSuccessful: 'Ijambo ry’ibanga ryasubijweho. Ubu ushobora kwinjira ukoresheje irishya.',
    phone: 'Telefoni',
    phoneNumber: 'Nimero ya telefoni',
    recoveryCodeSent: 'Niba nimero ibaho, kode yo kwemeza yoherejwe.',
    requestPasswordRecovery: 'Saba kugarura ijambo ry’ibanga',
    requestingCode: 'Harasabwa kode...',
    resendVerificationCode: 'Ongera wohereze kode yo kwemeza',
    resetPassword: 'Subizaho ijambo ry’ibanga',
    resetting: 'Birimo gusubizwaho...',
    returnToSignIn: 'Subira ku kwinjira',
    sendVerificationCodeFailed: 'Kohereza kode yo kwemeza byanze',
    verificationCode: 'Kode yo kwemeza'
  },
  'so-SO': {
    debugCode: 'Koodh debug',
    enterNewPassword: 'Geli eray sir cusub',
    enterPhoneFirst: 'Marka hore geli lambarka telefoonka',
    enterVerificationCode: 'Geli koodhka xaqiijinta',
    newPassword: 'Eray sir cusub',
    optionalPhoneNumber: 'Lambarka telefoonka (ikhtiyaari)',
    passwordRecoveryRequestFailed: 'Codsiga soo celinta erayga sirta ah wuu fashilmay',
    passwordResetFailed: 'Dib u dejinta erayga sirta ah way fashilantay',
    passwordResetSuccessful: 'Erayga sirta ah waa la beddelay. Hadda waxaad ku geli kartaa erayga sirta cusub.',
    phone: 'Telefoon',
    phoneNumber: 'Lambarka telefoonka',
    recoveryCodeSent: 'Haddii lambarku jiro, koodh xaqiijin ayaa la diray.',
    requestPasswordRecovery: 'Codso soo celinta erayga sirta ah',
    requestingCode: 'Koodh ayaa la codsanayaa...',
    resendVerificationCode: 'Dib u dir koodhka xaqiijinta',
    resetPassword: 'Dib u deji erayga sirta ah',
    resetting: 'Dib ayaa loo dejinayaa...',
    returnToSignIn: 'Ku noqo gelitaanka',
    sendVerificationCodeFailed: 'Dirista koodhka xaqiijinta way fashilantay',
    verificationCode: 'Koodhka xaqiijinta'
  },
  'sw-KE': {
    debugCode: 'Msimbo wa utatuzi',
    enterNewPassword: 'Weka nenosiri jipya',
    enterPhoneFirst: 'Weka nambari ya simu kwanza',
    enterVerificationCode: 'Weka msimbo wa uthibitishaji',
    newPassword: 'Nenosiri jipya',
    optionalPhoneNumber: 'Nambari ya simu (si lazima)',
    passwordRecoveryRequestFailed: 'Ombi la kurejesha nenosiri limeshindwa',
    passwordResetFailed: 'Kuweka upya nenosiri kumeshindikana',
    passwordResetSuccessful: 'Nenosiri limewekwa upya. Sasa unaweza kuingia kwa nenosiri jipya.',
    phone: 'Simu',
    phoneNumber: 'Nambari ya simu',
    recoveryCodeSent: 'Ikiwa nambari ipo, msimbo wa uthibitishaji umetumwa.',
    requestPasswordRecovery: 'Omba kurejesha nenosiri',
    requestingCode: 'Inaomba msimbo...',
    resendVerificationCode: 'Tuma tena msimbo wa uthibitishaji',
    resetPassword: 'Weka upya nenosiri',
    resetting: 'Inaweka upya...',
    returnToSignIn: 'Rudi kuingia',
    sendVerificationCodeFailed: 'Kutuma msimbo wa uthibitishaji kumeshindikana',
    verificationCode: 'Msimbo wa uthibitishaji'
  },
  'th-TH': {
    debugCode: 'รหัสดีบัก',
    enterNewPassword: 'กรอกรหัสผ่านใหม่',
    enterPhoneFirst: 'กรอกหมายเลขโทรศัพท์ก่อน',
    enterVerificationCode: 'กรอกรหัสยืนยัน',
    newPassword: 'รหัสผ่านใหม่',
    optionalPhoneNumber: 'หมายเลขโทรศัพท์ (ไม่บังคับ)',
    passwordRecoveryRequestFailed: 'ขอกู้คืนรหัสผ่านไม่สำเร็จ',
    passwordResetFailed: 'รีเซ็ตรหัสผ่านไม่สำเร็จ',
    passwordResetSuccessful: 'รีเซ็ตรหัสผ่านแล้ว คุณสามารถเข้าสู่ระบบด้วยรหัสผ่านใหม่ได้',
    phone: 'โทรศัพท์',
    phoneNumber: 'หมายเลขโทรศัพท์',
    recoveryCodeSent: 'หากหมายเลขนี้มีอยู่ ระบบได้ส่งรหัสยืนยันแล้ว',
    requestPasswordRecovery: 'ขอกู้คืนรหัสผ่าน',
    requestingCode: 'กำลังขอรหัส...',
    resendVerificationCode: 'ส่งรหัสยืนยันอีกครั้ง',
    resetPassword: 'รีเซ็ตรหัสผ่าน',
    resetting: 'กำลังรีเซ็ต...',
    returnToSignIn: 'กลับไปเข้าสู่ระบบ',
    sendVerificationCodeFailed: 'ส่งรหัสยืนยันไม่สำเร็จ',
    verificationCode: 'รหัสยืนยัน'
  },
  'tr-TR': {
    debugCode: 'Hata ayıklama kodu',
    enterNewPassword: 'Yeni parolayı girin',
    enterPhoneFirst: 'Önce telefon numarasını girin',
    enterVerificationCode: 'Doğrulama kodunu girin',
    newPassword: 'Yeni parola',
    optionalPhoneNumber: 'Telefon numarası (isteğe bağlı)',
    passwordRecoveryRequestFailed: 'Parola kurtarma isteği başarısız',
    passwordResetFailed: 'Parola sıfırlama başarısız',
    passwordResetSuccessful: 'Parola sıfırlandı. Yeni parolanızla giriş yapabilirsiniz.',
    phone: 'Telefon',
    phoneNumber: 'Telefon numarası',
    recoveryCodeSent: 'Numara varsa doğrulama kodu gönderildi.',
    requestPasswordRecovery: 'Parola kurtarma iste',
    requestingCode: 'Kod isteniyor...',
    resendVerificationCode: 'Doğrulama kodunu tekrar gönder',
    resetPassword: 'Parolayı sıfırla',
    resetting: 'Sıfırlanıyor...',
    returnToSignIn: 'Girişe dön',
    sendVerificationCodeFailed: 'Doğrulama kodu gönderilemedi',
    verificationCode: 'Doğrulama kodu'
  },
  'uk-UA': {
    debugCode: 'Код налагодження',
    enterNewPassword: 'Введіть новий пароль',
    enterPhoneFirst: 'Спочатку введіть номер телефону',
    enterVerificationCode: 'Введіть код підтвердження',
    newPassword: 'Новий пароль',
    optionalPhoneNumber: 'Номер телефону (необов’язково)',
    passwordRecoveryRequestFailed: 'Не вдалося надіслати запит на відновлення пароля',
    passwordResetFailed: 'Не вдалося скинути пароль',
    passwordResetSuccessful: 'Пароль скинуто. Тепер ви можете увійти з новим паролем.',
    phone: 'Телефон',
    phoneNumber: 'Номер телефону',
    recoveryCodeSent: 'Якщо номер існує, код підтвердження надіслано.',
    requestPasswordRecovery: 'Запросити відновлення пароля',
    requestingCode: 'Запит коду...',
    resendVerificationCode: 'Надіслати код повторно',
    resetPassword: 'Скинути пароль',
    resetting: 'Скидання...',
    returnToSignIn: 'Повернутися до входу',
    sendVerificationCodeFailed: 'Не вдалося надіслати код підтвердження',
    verificationCode: 'Код підтвердження'
  },
  'vi-VN': {
    debugCode: 'Mã gỡ lỗi',
    enterNewPassword: 'Nhập mật khẩu mới',
    enterPhoneFirst: 'Nhập số điện thoại trước',
    enterVerificationCode: 'Nhập mã xác minh',
    newPassword: 'Mật khẩu mới',
    optionalPhoneNumber: 'Số điện thoại (tùy chọn)',
    passwordRecoveryRequestFailed: 'Yêu cầu khôi phục mật khẩu thất bại',
    passwordResetFailed: 'Đặt lại mật khẩu thất bại',
    passwordResetSuccessful: 'Đã đặt lại mật khẩu. Bạn có thể đăng nhập bằng mật khẩu mới.',
    phone: 'Điện thoại',
    phoneNumber: 'Số điện thoại',
    recoveryCodeSent: 'Nếu số này tồn tại, mã xác minh đã được gửi.',
    requestPasswordRecovery: 'Yêu cầu khôi phục mật khẩu',
    requestingCode: 'Đang yêu cầu mã...',
    resendVerificationCode: 'Gửi lại mã xác minh',
    resetPassword: 'Đặt lại mật khẩu',
    resetting: 'Đang đặt lại...',
    returnToSignIn: 'Quay lại đăng nhập',
    sendVerificationCodeFailed: 'Không gửi được mã xác minh',
    verificationCode: 'Mã xác minh'
  },
  'yo-NG': {
    debugCode: 'Koodu debug',
    enterNewPassword: 'Tẹ ọrọ aṣínà tuntun sii',
    enterPhoneFirst: 'Tẹ nọmba foonu sii kọ́kọ́',
    enterVerificationCode: 'Tẹ koodu ìmúdájú sii',
    newPassword: 'Ọrọ aṣínà tuntun',
    optionalPhoneNumber: 'Nọmba foonu (iyan)',
    passwordRecoveryRequestFailed: 'Ìbéèrè imularada ọrọ aṣínà kuna',
    passwordResetFailed: 'Atunto ọrọ aṣínà kuna',
    passwordResetSuccessful: 'A ti tún ọrọ aṣínà ṣe. O le wọlé pẹlu ọrọ aṣínà tuntun bayi.',
    phone: 'Foonu',
    phoneNumber: 'Nọmba foonu',
    recoveryCodeSent: 'Ti nọmba naa ba wa, a ti fi koodu ìmúdájú ranṣẹ.',
    requestPasswordRecovery: 'Bẹ̀rẹ̀ imularada ọrọ aṣínà',
    requestingCode: 'Ń bẹ̀rẹ̀ koodu...',
    resendVerificationCode: 'Fi koodu ìmúdájú ranṣẹ lẹẹkansi',
    resetPassword: 'Tún ọrọ aṣínà ṣe',
    resetting: 'Ń tún ṣe...',
    returnToSignIn: 'Pada si wọlé',
    sendVerificationCodeFailed: 'Fifiranṣẹ koodu ìmúdájú kuna',
    verificationCode: 'Koodu ìmúdájú'
  },
  'zh-CN': {
    debugCode: '调试验证码',
    enterNewPassword: '请输入新密码',
    enterPhoneFirst: '请先输入手机号',
    enterVerificationCode: '请输入验证码',
    newPassword: '新密码',
    optionalPhoneNumber: '手机号（选填）',
    passwordRecoveryRequestFailed: '找回密码请求失败',
    passwordResetFailed: '重置密码失败',
    passwordResetSuccessful: '密码已重置，现在可以使用新密码登录。',
    phone: '手机号',
    phoneNumber: '手机号',
    recoveryCodeSent: '如果该号码存在，验证码已发送。',
    requestPasswordRecovery: '找回密码',
    requestingCode: '正在获取验证码...',
    resendVerificationCode: '重新发送验证码',
    resetPassword: '重置密码',
    resetting: '正在重置...',
    returnToSignIn: '返回登录',
    sendVerificationCodeFailed: '验证码发送失败',
    verificationCode: '验证码'
  },
  'zh-TW': {
    debugCode: '偵錯驗證碼',
    enterNewPassword: '請輸入新密碼',
    enterPhoneFirst: '請先輸入手機號碼',
    enterVerificationCode: '請輸入驗證碼',
    newPassword: '新密碼',
    optionalPhoneNumber: '手機號碼（選填）',
    passwordRecoveryRequestFailed: '找回密碼請求失敗',
    passwordResetFailed: '重設密碼失敗',
    passwordResetSuccessful: '密碼已重設，現在可以使用新密碼登入。',
    phone: '手機',
    phoneNumber: '手機號碼',
    recoveryCodeSent: '如果該號碼存在，驗證碼已發送。',
    requestPasswordRecovery: '找回密碼',
    requestingCode: '正在取得驗證碼...',
    resendVerificationCode: '重新發送驗證碼',
    resetPassword: '重設密碼',
    resetting: '正在重設...',
    returnToSignIn: '返回登入',
    sendVerificationCodeFailed: '驗證碼發送失敗',
    verificationCode: '驗證碼'
  },
  'zu-ZA': {
    debugCode: 'Ikhodi yokulungisa',
    enterNewPassword: 'Faka iphasiwedi entsha',
    enterPhoneFirst: 'Faka inombolo yocingo kuqala',
    enterVerificationCode: 'Faka ikhodi yokuqinisekisa',
    newPassword: 'Iphasiwedi entsha',
    optionalPhoneNumber: 'Inombolo yocingo (uyazikhethela)',
    passwordRecoveryRequestFailed: 'Isicelo sokubuyisa iphasiwedi sehlulekile',
    passwordResetFailed: 'Ukusetha kabusha iphasiwedi kwehlulekile',
    passwordResetSuccessful: 'Iphasiwedi isethwe kabusha. Manje ungangena ngephasiwedi entsha.',
    phone: 'Ucingo',
    phoneNumber: 'Inombolo yocingo',
    recoveryCodeSent: 'Uma le nombolo ikhona, ikhodi yokuqinisekisa ithunyelwe.',
    requestPasswordRecovery: 'Cela ukubuyiswa kwephasiwedi',
    requestingCode: 'Kucelwa ikhodi...',
    resendVerificationCode: 'Thumela futhi ikhodi yokuqinisekisa',
    resetPassword: 'Setha kabusha iphasiwedi',
    resetting: 'Kuyasethwa kabusha...',
    returnToSignIn: 'Buyela ekungeneni',
    sendVerificationCodeFailed: 'Ukuthumela ikhodi yokuqinisekisa kwehlulekile',
    verificationCode: 'Ikhodi yokuqinisekisa'
  }
} satisfies Record<LanguageCode, AuthFlowCopy>;

export function getAuthFlowCopy(language: LanguageCode) {
  return AUTH_FLOW_COPY_BY_LANGUAGE[language] ?? AUTH_FLOW_COPY_BY_LANGUAGE['en-US'];
}
