import { getLanguageLabel, translate, type LanguageCode, type TranslationKey } from './i18n';

export type PageTermKey =
  | 'accountOptions'
  | 'actions'
  | 'active'
  | 'admin'
  | 'allModels'
  | 'allStatuses'
  | 'allTokens'
  | 'allUsableModels'
  | 'apply'
  | 'availableModels'
  | 'balance'
  | 'billing'
  | 'cancel'
  | 'charged'
  | 'close'
  | 'configured'
  | 'copy'
  | 'copyAllModels'
  | 'copyModelName'
  | 'createdAt'
  | 'createToken'
  | 'currentPassword'
  | 'delete'
  | 'deleteSelected'
  | 'deleted'
  | 'deliveryRecords'
  | 'disabled'
  | 'edit'
  | 'editToken'
  | 'emptyLogs'
  | 'emptyModels'
  | 'emptyRecords'
  | 'emptyTokens'
  | 'enabled'
  | 'error'
  | 'event'
  | 'eventSubscriptions'
  | 'expired'
  | 'expiresAt'
  | 'export'
  | 'failed'
  | 'failedCalls'
  | 'filteredCharges'
  | 'filters'
  | 'free'
  | 'input'
  | 'calls'
  | 'cost'
  | 'currentUser'
  | 'lastLogin'
  | 'lastLoginIp'
  | 'lastUsed'
  | 'leaderboard'
  | 'loading'
  | 'lowBalanceAlert'
  | 'mergedChargeTotal'
  | 'model'
  | 'modelConfig'
  | 'modelDistribution'
  | 'modelList'
  | 'modelPriceUpdates'
  | 'modelSearch'
  | 'name'
  | 'neverExpires'
  | 'newPassword'
  | 'nextPage'
  | 'noCopyModels'
  | 'noData'
  | 'noLimit'
  | 'notConfigured'
  | 'notEnabled'
  | 'note'
  | 'notificationChannels'
  | 'notificationSettings'
  | 'output'
  | 'password'
  | 'previousPage'
  | 'promotions'
  | 'quota'
  | 'rank'
  | 'recharge'
  | 'rechargeCode'
  | 'records'
  | 'refresh'
  | 'remainingQuota'
  | 'reset'
  | 'resetKey'
  | 'save'
  | 'saveSettings'
  | 'saving'
  | 'search'
  | 'securityAlerts'
  | 'select'
  | 'send'
  | 'sent'
  | 'status'
  | 'systemAnnouncements'
  | 'systemToken'
  | 'target'
  | 'test'
  | 'testing'
  | 'threshold'
  | 'time'
  | 'timeRange'
  | 'timezone'
  | 'token'
  | 'tokenManagement'
  | 'totalSpend'
  | 'totalTokens'
  | 'unknownMetering'
  | 'upstreamTokens'
  | 'usageDetails'
  | 'usageLogs'
  | 'user'
  | 'userInfo'
  | 'visibleRows'
  | 'webhook';

const ENGLISH_TERMS = {
  accountOptions: 'Account options',
  actions: 'Actions',
  active: 'Active',
  admin: 'Admin',
  allModels: 'All models',
  allStatuses: 'All statuses',
  allTokens: 'All tokens',
  allUsableModels: 'All available models',
  apply: 'Apply',
  availableModels: 'Available models',
  balance: 'Balance',
  billing: 'Billing',
  cancel: 'Cancel',
  charged: 'Charged',
  close: 'Close',
  configured: 'Configured',
  copy: 'Copy',
  copyAllModels: 'Copy all models',
  copyModelName: 'Copy model name',
  createdAt: 'Created',
  createToken: 'Create token',
  currentPassword: 'Current password',
  delete: 'Delete',
  deleteSelected: 'Delete selected',
  deleted: 'Deleted',
  deliveryRecords: 'Delivery records',
  disabled: 'Disabled',
  edit: 'Edit',
  editToken: 'Edit token',
  emptyLogs: 'No usage logs',
  emptyModels: 'No models',
  emptyRecords: 'No records',
  emptyTokens: 'No tokens',
  enabled: 'Enabled',
  error: 'Error',
  event: 'Event',
  eventSubscriptions: 'Event subscriptions',
  expired: 'Expired',
  expiresAt: 'Expires',
  export: 'Export',
  failed: 'Failed',
  failedCalls: 'Failed calls',
  filteredCharges: 'Filtered charges',
  filters: 'Filters',
  free: 'Free',
  input: 'Input',
  calls: 'Calls',
  cost: 'Cost',
  currentUser: 'You',
  lastLogin: 'Last login time',
  lastLoginIp: 'Last login IP',
  lastUsed: 'Last used',
  leaderboard: 'Token leaderboard',
  loading: 'Loading',
  lowBalanceAlert: 'Low balance alert',
  mergedChargeTotal: 'Merged charge total',
  model: 'Model',
  modelConfig: 'Model configuration',
  modelDistribution: 'Model distribution',
  modelList: 'Model list',
  modelPriceUpdates: 'Model price updates',
  modelSearch: 'Search models',
  name: 'Name',
  neverExpires: 'Never expires',
  newPassword: 'New password',
  nextPage: 'Next page',
  noCopyModels: 'No models to copy',
  noData: 'No data',
  noLimit: 'Unlimited',
  notConfigured: 'Not configured',
  notEnabled: 'Disabled',
  note: 'Note',
  notificationChannels: 'Notification channels',
  notificationSettings: 'Notification settings',
  output: 'Output',
  password: 'Password',
  previousPage: 'Previous page',
  promotions: 'Promotions',
  quota: 'Quota',
  rank: 'Rank',
  recharge: 'Top up',
  rechargeCode: 'Recharge code',
  records: 'Records',
  refresh: 'Refresh',
  remainingQuota: 'Remaining quota',
  reset: 'Reset',
  resetKey: 'Reset key',
  save: 'Save',
  saveSettings: 'Save settings',
  saving: 'Saving',
  search: 'Search',
  securityAlerts: 'Security alerts',
  select: 'Select',
  send: 'Send',
  sent: 'Sent',
  status: 'Status',
  systemAnnouncements: 'System announcements',
  systemToken: 'System tokens',
  target: 'Target',
  test: 'Test',
  testing: 'Testing',
  threshold: 'Threshold',
  time: 'Time',
  timeRange: 'Time range',
  timezone: 'Timezone',
  token: 'Token',
  tokenManagement: 'Token management',
  totalSpend: 'Total spend',
  totalTokens: 'Total tokens',
  unknownMetering: 'Metering unknown',
  upstreamTokens: 'Upstream tokens',
  usageDetails: 'Usage details',
  usageLogs: 'Usage logs',
  user: 'User',
  userInfo: 'User information',
  visibleRows: 'Rows',
  webhook: 'Webhook'
} satisfies Record<PageTermKey, string>;

const ZH_CN_PAGE_TERMS = {
  accountOptions: '账户选项',
  actions: '操作',
  active: '启用',
  admin: '管理员',
  allModels: '全部模型',
  allStatuses: '全部状态',
  allTokens: '全部令牌',
  allUsableModels: '全部可用模型',
  apply: '应用',
  availableModels: '可用模型',
  balance: '余额',
  billing: '计费',
  cancel: '取消',
  calls: '调用',
  charged: '已计费',
  close: '关闭',
  configured: '已配置',
  copy: '复制',
  copyAllModels: '复制全部模型',
  copyModelName: '复制模型名',
  cost: '成本',
  createdAt: '创建时间',
  createToken: '创建令牌',
  currentPassword: '当前密码',
  currentUser: '当前用户',
  delete: '删除',
  deleteSelected: '删除所选',
  deleted: '已删除',
  deliveryRecords: '投递记录',
  disabled: '已禁用',
  edit: '编辑',
  editToken: '编辑令牌',
  emptyLogs: '暂无使用日志',
  emptyModels: '暂无模型',
  emptyRecords: '暂无记录',
  emptyTokens: '暂无令牌',
  enabled: '已启用',
  error: '错误',
  event: '事件',
  eventSubscriptions: '事件订阅',
  expired: '已过期',
  expiresAt: '过期时间',
  export: '导出',
  failed: '失败',
  failedCalls: '失败调用',
  filteredCharges: '筛选计费',
  filters: '筛选',
  free: '免费',
  input: '输入',
  lastLogin: '最后登录时间',
  lastLoginIp: '最后登录 IP',
  lastUsed: '最后使用',
  leaderboard: '令牌排行榜',
  loading: '加载中',
  lowBalanceAlert: '低余额提醒',
  mergedChargeTotal: '合并计费总额',
  model: '模型',
  modelConfig: '模型配置',
  modelDistribution: '模型分布',
  modelList: '模型列表',
  modelPriceUpdates: '模型价格更新',
  modelSearch: '搜索模型',
  name: '名称',
  neverExpires: '永不过期',
  newPassword: '新密码',
  nextPage: '下一页',
  noCopyModels: '没有可复制模型',
  noData: '暂无数据',
  noLimit: '不限制',
  notConfigured: '未配置',
  notEnabled: '已禁用',
  note: '备注',
  notificationChannels: '通知渠道',
  notificationSettings: '通知设置',
  output: '输出',
  password: '密码',
  previousPage: '上一页',
  promotions: '活动',
  quota: '配额',
  rank: '排名',
  recharge: '充值',
  rechargeCode: '充值码',
  records: '记录',
  refresh: '刷新',
  remainingQuota: '剩余配额',
  reset: '重置',
  resetKey: '重置密钥',
  save: '保存',
  saveSettings: '保存设置',
  saving: '保存中',
  search: '搜索',
  securityAlerts: '安全提醒',
  select: '选择',
  send: '发送',
  sent: '已发送',
  status: '状态',
  systemAnnouncements: '系统公告',
  systemToken: '系统令牌',
  target: '目标',
  test: '测试',
  testing: '测试中',
  threshold: '阈值',
  time: '时间',
  timeRange: '时间范围',
  timezone: '时区',
  token: '令牌',
  tokenManagement: '令牌管理',
  totalSpend: '总花费',
  totalTokens: '总令牌',
  unknownMetering: '未知计量',
  upstreamTokens: '上游令牌',
  usageDetails: '使用详情',
  usageLogs: '使用日志',
  user: '用户',
  userInfo: '用户信息',
  visibleRows: '可见行',
  webhook: 'Webhook'
} satisfies Record<PageTermKey, string>;

const ZH_TW_PAGE_TERMS = {
  accountOptions: '帳戶選項',
  actions: '操作',
  active: '啟用',
  admin: '管理員',
  allModels: '全部模型',
  allStatuses: '全部狀態',
  allTokens: '全部權杖',
  allUsableModels: '全部可用模型',
  apply: '套用',
  availableModels: '可用模型',
  balance: '餘額',
  billing: '計費',
  cancel: '取消',
  calls: '呼叫',
  charged: '已計費',
  close: '關閉',
  configured: '已設定',
  copy: '複製',
  copyAllModels: '複製全部模型',
  copyModelName: '複製模型名稱',
  cost: '成本',
  createdAt: '建立時間',
  createToken: '建立權杖',
  currentPassword: '目前密碼',
  currentUser: '目前使用者',
  delete: '刪除',
  deleteSelected: '刪除所選',
  deleted: '已刪除',
  deliveryRecords: '投遞記錄',
  disabled: '已停用',
  edit: '編輯',
  editToken: '編輯權杖',
  emptyLogs: '暫無使用日誌',
  emptyModels: '暫無模型',
  emptyRecords: '暫無記錄',
  emptyTokens: '暫無權杖',
  enabled: '已啟用',
  error: '錯誤',
  event: '事件',
  eventSubscriptions: '事件訂閱',
  expired: '已過期',
  expiresAt: '過期時間',
  export: '匯出',
  failed: '失敗',
  failedCalls: '失敗呼叫',
  filteredCharges: '篩選計費',
  filters: '篩選',
  free: '免費',
  input: '輸入',
  lastLogin: '最後登入時間',
  lastLoginIp: '最後登入 IP',
  lastUsed: '最後使用',
  leaderboard: '權杖排行榜',
  loading: '載入中',
  lowBalanceAlert: '低餘額提醒',
  mergedChargeTotal: '合併計費總額',
  model: '模型',
  modelConfig: '模型設定',
  modelDistribution: '模型分布',
  modelList: '模型列表',
  modelPriceUpdates: '模型價格更新',
  modelSearch: '搜尋模型',
  name: '名稱',
  neverExpires: '永不過期',
  newPassword: '新密碼',
  nextPage: '下一頁',
  noCopyModels: '沒有可複製模型',
  noData: '暫無資料',
  noLimit: '不限制',
  notConfigured: '未設定',
  notEnabled: '已停用',
  note: '備註',
  notificationChannels: '通知渠道',
  notificationSettings: '通知設定',
  output: '輸出',
  password: '密碼',
  previousPage: '上一頁',
  promotions: '活動',
  quota: '配額',
  rank: '排名',
  recharge: '儲值',
  rechargeCode: '儲值碼',
  records: '記錄',
  refresh: '重新整理',
  remainingQuota: '剩餘配額',
  reset: '重置',
  resetKey: '重置金鑰',
  save: '儲存',
  saveSettings: '儲存設定',
  saving: '儲存中',
  search: '搜尋',
  securityAlerts: '安全提醒',
  select: '選擇',
  send: '傳送',
  sent: '已傳送',
  status: '狀態',
  systemAnnouncements: '系統公告',
  systemToken: '系統權杖',
  target: '目標',
  test: '測試',
  testing: '測試中',
  threshold: '門檻',
  time: '時間',
  timeRange: '時間範圍',
  timezone: '時區',
  token: '權杖',
  tokenManagement: '權杖管理',
  totalSpend: '總花費',
  totalTokens: '總權杖',
  unknownMetering: '未知計量',
  upstreamTokens: '上游權杖',
  usageDetails: '使用詳情',
  usageLogs: '使用日誌',
  user: '使用者',
  userInfo: '使用者資訊',
  visibleRows: '可見列',
  webhook: 'Webhook'
} satisfies Record<PageTermKey, string>;

const TRANSLATION_KEYS: Partial<Record<PageTermKey, TranslationKey>> = {
  accountOptions: 'nav.account',
  admin: 'role.admin',
  close: 'common.close',
  loading: 'common.loading',
  notificationSettings: 'nav.notificationSettings',
  password: 'auth.password',
  recharge: 'nav.recharge',
  refresh: 'common.refresh',
  token: 'nav.token',
  tokenManagement: 'nav.token',
  usageLogs: 'nav.log',
  user: 'role.user',
  userInfo: 'nav.profile'
};

const LOCAL_TERMS: Partial<Record<LanguageCode, Partial<Record<PageTermKey, string>>>> = {
  'zh-CN': ZH_CN_PAGE_TERMS,
  'zh-TW': ZH_TW_PAGE_TERMS,
  'es-ES': {
    actions: 'Acciones',
    active: 'Activo',
    allModels: 'Todos los modelos',
    allStatuses: 'Todos los estados',
    allTokens: 'Todos los tokens',
    apply: 'Aplicar',
    availableModels: 'Modelos disponibles',
    balance: 'Saldo',
    billing: 'Facturacion',
    cancel: 'Cancelar',
    copy: 'Copiar',
    delete: 'Eliminar',
    edit: 'Editar',
    error: 'Error',
    event: 'Evento',
    failed: 'Fallido',
    filters: 'Filtros',
    input: 'Entrada',
    model: 'Modelo',
    name: 'Nombre',
    output: 'Salida',
    quota: 'Cuota',
    save: 'Guardar',
    search: 'Buscar',
    select: 'Seleccionar',
    status: 'Estado',
    time: 'Hora',
    timezone: 'Zona horaria'
  },
  'fr-FR': {
    actions: 'Actions',
    active: 'Actif',
    allModels: 'Tous les modeles',
    allStatuses: 'Tous les statuts',
    allTokens: 'Tous les tokens',
    apply: 'Appliquer',
    availableModels: 'Modeles disponibles',
    balance: 'Solde',
    billing: 'Facturation',
    cancel: 'Annuler',
    copy: 'Copier',
    delete: 'Supprimer',
    edit: 'Modifier',
    error: 'Erreur',
    event: 'Evenement',
    failed: 'Echec',
    filters: 'Filtres',
    input: 'Entree',
    model: 'Modele',
    name: 'Nom',
    output: 'Sortie',
    quota: 'Quota',
    save: 'Enregistrer',
    search: 'Rechercher',
    select: 'Selectionner',
    status: 'Statut',
    time: 'Heure',
    timezone: 'Fuseau horaire'
  },
  'de-DE': {
    actions: 'Aktionen',
    active: 'Aktiv',
    allModels: 'Alle Modelle',
    allStatuses: 'Alle Status',
    allTokens: 'Alle Token',
    apply: 'Anwenden',
    availableModels: 'Verfugbare Modelle',
    balance: 'Guthaben',
    billing: 'Abrechnung',
    cancel: 'Abbrechen',
    copy: 'Kopieren',
    delete: 'Loschen',
    edit: 'Bearbeiten',
    error: 'Fehler',
    event: 'Ereignis',
    failed: 'Fehlgeschlagen',
    filters: 'Filter',
    input: 'Eingabe',
    model: 'Modell',
    name: 'Name',
    output: 'Ausgabe',
    quota: 'Kontingent',
    save: 'Speichern',
    search: 'Suchen',
    select: 'Auswahlen',
    status: 'Status',
    time: 'Zeit',
    timezone: 'Zeitzone'
  },
  'pt-BR': {
    actions: 'Acoes',
    active: 'Ativo',
    allModels: 'Todos os modelos',
    allStatuses: 'Todos os status',
    allTokens: 'Todos os tokens',
    apply: 'Aplicar',
    availableModels: 'Modelos disponiveis',
    balance: 'Saldo',
    billing: 'Cobranca',
    cancel: 'Cancelar',
    copy: 'Copiar',
    delete: 'Excluir',
    edit: 'Editar',
    error: 'Erro',
    event: 'Evento',
    failed: 'Falhou',
    filters: 'Filtros',
    input: 'Entrada',
    model: 'Modelo',
    name: 'Nome',
    output: 'Saida',
    quota: 'Cota',
    save: 'Salvar',
    search: 'Pesquisar',
    select: 'Selecionar',
    status: 'Status',
    time: 'Hora',
    timezone: 'Fuso horario'
  },
  'ja-JP': {
    actions: '操作',
    active: '有効',
    allModels: 'すべてのモデル',
    allStatuses: 'すべてのステータス',
    allTokens: 'すべてのトークン',
    apply: '適用',
    availableModels: '利用可能なモデル',
    balance: '残高',
    billing: '課金',
    cancel: 'キャンセル',
    charged: '課金済み',
    configured: '設定済み',
    copy: 'コピー',
    copyAllModels: 'すべてのモデルをコピー',
    copyModelName: 'モデル名をコピー',
    createdAt: '作成日時',
    createToken: 'トークンを作成',
    currentPassword: '現在のパスワード',
    delete: '削除',
    deleteSelected: '選択項目を削除',
    deleted: '削除済み',
    deliveryRecords: '配信記録',
    disabled: '無効',
    edit: '編集',
    editToken: 'トークンを編集',
    emptyLogs: '利用ログはありません',
    emptyModels: 'モデルはありません',
    emptyRecords: '記録はありません',
    emptyTokens: 'トークンはありません',
    enabled: '有効',
    error: 'エラー',
    event: 'イベント',
    eventSubscriptions: 'イベント購読',
    expired: '期限切れ',
    expiresAt: '有効期限',
    export: 'エクスポート',
    failed: '失敗',
    failedCalls: '失敗した呼び出し',
    filteredCharges: 'フィルター範囲の課金',
    filters: 'フィルター',
    free: '無料',
    input: '入力',
    lastLogin: '最終ログイン時間',
    lastLoginIp: '最終ログイン IP',
    lastUsed: '最終使用',
    lowBalanceAlert: '残高不足アラート',
    mergedChargeTotal: '統合課金合計',
    model: 'モデル',
    modelConfig: 'モデル設定',
    modelDistribution: 'モデル分布',
    modelList: 'モデル一覧',
    modelPriceUpdates: 'モデル価格更新',
    modelSearch: 'モデルを検索',
    name: '名前',
    neverExpires: '期限なし',
    newPassword: '新しいパスワード',
    nextPage: '次のページ',
    noCopyModels: 'コピーできるモデルはありません',
    noData: 'データはありません',
    noLimit: '無制限',
    notConfigured: '未設定',
    notEnabled: '無効',
    note: 'メモ',
    notificationChannels: '通知チャネル',
    output: '出力',
    previousPage: '前のページ',
    promotions: 'プロモーション',
    quota: '上限',
    recharge: 'チャージ',
    rechargeCode: 'チャージコード',
    records: '記録',
    remainingQuota: '残り上限',
    reset: 'リセット',
    resetKey: 'キーをリセット',
    save: '保存',
    saveSettings: '設定を保存',
    saving: '保存中',
    search: '検索',
    securityAlerts: 'セキュリティアラート',
    select: '選択',
    send: '送信',
    sent: '送信済み',
    status: 'ステータス',
    systemAnnouncements: 'システム公告',
    systemToken: 'システムトークン',
    target: 'ターゲット',
    test: 'テスト',
    testing: 'テスト中',
    threshold: 'しきい値',
    time: '時間',
    timeRange: '時間範囲',
    timezone: 'タイムゾーン',
    totalSpend: '累計消費',
    totalTokens: '合計トークン',
    unknownMetering: '計量不明',
    upstreamTokens: '上流トークン',
    usageDetails: '利用明細',
    visibleRows: '行数',
    webhook: 'Webhook'
  },
  'ko-KR': {
    actions: '작업',
    active: '활성',
    allModels: '모든 모델',
    allStatuses: '모든 상태',
    allTokens: '모든 토큰',
    apply: '적용',
    availableModels: '사용 가능한 모델',
    balance: '잔액',
    billing: '과금',
    cancel: '취소',
    copy: '복사',
    delete: '삭제',
    edit: '수정',
    error: '오류',
    event: '이벤트',
    failed: '실패',
    filters: '필터',
    input: '입력',
    model: '모델',
    name: '이름',
    output: '출력',
    quota: '한도',
    save: '저장',
    search: '검색',
    select: '선택',
    status: '상태',
    time: '시간',
    timezone: '시간대'
  },
  'ru-RU': {
    actions: 'Действия',
    active: 'Активен',
    allModels: 'Все модели',
    allStatuses: 'Все статусы',
    allTokens: 'Все токены',
    apply: 'Применить',
    availableModels: 'Доступные модели',
    balance: 'Баланс',
    billing: 'Биллинг',
    cancel: 'Отмена',
    copy: 'Копировать',
    delete: 'Удалить',
    edit: 'Изменить',
    error: 'Ошибка',
    event: 'Событие',
    failed: 'Ошибка',
    filters: 'Фильтры',
    input: 'Ввод',
    model: 'Модель',
    name: 'Имя',
    output: 'Вывод',
    quota: 'Квота',
    save: 'Сохранить',
    search: 'Поиск',
    select: 'Выбрать',
    status: 'Статус',
    time: 'Время',
    timezone: 'Часовой пояс'
  },
  'ar-EG': {
    actions: 'الإجراءات',
    active: 'نشط',
    allModels: 'كل النماذج',
    allStatuses: 'كل الحالات',
    allTokens: 'كل الرموز',
    apply: 'تطبيق',
    availableModels: 'النماذج المتاحة',
    balance: 'الرصيد',
    billing: 'الفوترة',
    cancel: 'إلغاء',
    copy: 'نسخ',
    delete: 'حذف',
    edit: 'تعديل',
    error: 'خطأ',
    event: 'حدث',
    failed: 'فشل',
    filters: 'مرشحات',
    input: 'إدخال',
    model: 'نموذج',
    name: 'الاسم',
    output: 'إخراج',
    quota: 'حصة',
    save: 'حفظ',
    search: 'بحث',
    select: 'اختيار',
    status: 'الحالة',
    time: 'الوقت',
    timezone: 'المنطقة الزمنية'
  }
};

const EXTRA_LOCAL_TERMS: Partial<Record<LanguageCode, Partial<Record<PageTermKey, string>>>> = {
  'es-ES': {
    configured: 'Configurado',
    createdAt: 'Creado',
    deliveryRecords: 'Registros de entrega',
    disabled: 'Deshabilitado',
    emptyLogs: 'Sin registros de uso',
    emptyModels: 'Sin modelos',
    emptyRecords: 'Sin registros',
    emptyTokens: 'Sin tokens',
    enabled: 'Habilitado',
    eventSubscriptions: 'Suscripciones de eventos',
    expiresAt: 'Vence',
    export: 'Exportar',
    free: 'Gratis',
    lastUsed: 'Ultimo uso',
    lowBalanceAlert: 'Alerta de saldo bajo',
    modelPriceUpdates: 'Actualizaciones de precio de modelos',
    notificationChannels: 'Canales de notificacion',
    notConfigured: 'No configurado',
    notEnabled: 'Deshabilitado',
    promotions: 'Promociones',
    rechargeCode: 'Codigo de recarga',
    records: 'Registros',
    remainingQuota: 'Cuota restante',
    reset: 'Restablecer',
    saveSettings: 'Guardar configuracion',
    securityAlerts: 'Alertas de seguridad',
    send: 'Enviar',
    sent: 'Enviado',
    systemAnnouncements: 'Anuncios del sistema',
    target: 'Objetivo',
    threshold: 'Umbral',
    totalTokens: 'Tokens totales',
    usageDetails: 'Detalles de uso',
    visibleRows: 'Filas'
  },
  'fr-FR': {
    configured: 'Configure',
    createdAt: 'Cree',
    deliveryRecords: 'Registres de livraison',
    disabled: 'Desactive',
    emptyLogs: 'Aucun journal',
    emptyModels: 'Aucun modele',
    emptyRecords: 'Aucun enregistrement',
    emptyTokens: 'Aucun token',
    enabled: 'Active',
    eventSubscriptions: 'Abonnements aux evenements',
    expiresAt: 'Expire',
    export: 'Exporter',
    free: 'Gratuit',
    lastUsed: 'Derniere utilisation',
    notificationChannels: 'Canaux de notification',
    rechargeCode: 'Code de recharge',
    records: 'Enregistrements',
    remainingQuota: 'Quota restant',
    reset: 'Reinitialiser',
    send: 'Envoyer',
    sent: 'Envoye',
    totalTokens: 'Tokens totaux',
    usageDetails: 'Details d utilisation',
    visibleRows: 'Lignes'
  },
  'de-DE': {
    configured: 'Konfiguriert',
    createdAt: 'Erstellt',
    deliveryRecords: 'Zustellprotokolle',
    disabled: 'Deaktiviert',
    emptyLogs: 'Keine Nutzungsprotokolle',
    emptyModels: 'Keine Modelle',
    emptyRecords: 'Keine Eintraege',
    emptyTokens: 'Keine Tokens',
    enabled: 'Aktiviert',
    eventSubscriptions: 'Ereignis-Abos',
    expiresAt: 'Laeuft ab',
    export: 'Exportieren',
    free: 'Kostenlos',
    lastUsed: 'Zuletzt genutzt',
    notificationChannels: 'Benachrichtigungskanaele',
    rechargeCode: 'Aufladecode',
    records: 'Eintraege',
    remainingQuota: 'Restkontingent',
    reset: 'Zuruecksetzen',
    send: 'Senden',
    sent: 'Gesendet',
    totalTokens: 'Tokens gesamt',
    usageDetails: 'Nutzungsdetails',
    visibleRows: 'Zeilen'
  },
  'pt-BR': {
    configured: 'Configurado',
    createdAt: 'Criado',
    deliveryRecords: 'Registros de entrega',
    disabled: 'Desativado',
    emptyLogs: 'Sem logs de uso',
    emptyModels: 'Sem modelos',
    emptyRecords: 'Sem registros',
    emptyTokens: 'Sem tokens',
    enabled: 'Ativado',
    eventSubscriptions: 'Assinaturas de eventos',
    expiresAt: 'Expira',
    export: 'Exportar',
    free: 'Gratis',
    lastUsed: 'Ultimo uso',
    notificationChannels: 'Canais de notificacao',
    rechargeCode: 'Codigo de recarga',
    records: 'Registros',
    remainingQuota: 'Cota restante',
    reset: 'Redefinir',
    send: 'Enviar',
    sent: 'Enviado',
    totalTokens: 'Tokens totais',
    usageDetails: 'Detalhes de uso',
    visibleRows: 'Linhas'
  },
  'ko-KR': {
    rechargeCode: '충전 코드',
    records: '기록',
    send: '보내기',
    sent: '보냄'
  },
  'ru-RU': {
    rechargeCode: 'Код пополнения',
    records: 'Записи',
    send: 'Отправить',
    sent: 'Отправлено'
  },
  'ar-EG': {
    charged: 'محاسب',
    createdAt: 'تم الإنشاء',
    emptyTokens: 'لا توجد رموز',
    expiresAt: 'ينتهي',
    lastUsed: 'آخر استخدام',
    nextPage: 'الصفحة التالية',
    previousPage: 'الصفحة السابقة',
    rechargeCode: 'كود الشحن',
    records: 'السجلات',
    remainingQuota: 'الحصة المتبقية',
    send: 'إرسال',
    sent: 'تم الإرسال',
    visibleRows: 'صفوف'
  },
  'sw-KE': {
    actions: 'Vitendo',
    active: 'Inatumika',
    allModels: 'Miundo yote',
    allStatuses: 'Hali zote',
    allTokens: 'Tokeni zote',
    apply: 'Tumia',
    availableModels: 'Miundo inayopatikana',
    balance: 'Salio',
    billing: 'Malipo',
    cancel: 'Ghairi',
    copy: 'Nakili',
    delete: 'Futa',
    edit: 'Hariri',
    error: 'Hitilafu',
    event: 'Tukio',
    failed: 'Imeshindwa',
    filters: 'Vichujio',
    input: 'Ingizo',
    model: 'Muundo',
    name: 'Jina',
    output: 'Matokeo',
    quota: 'Kikomo',
    rechargeCode: 'Msimbo wa kujaza',
    records: 'Rekodi',
    save: 'Hifadhi',
    search: 'Tafuta',
    select: 'Chagua',
    send: 'Tuma',
    status: 'Hali',
    time: 'Muda',
    timezone: 'Saa za eneo'
  },
  'am-ET': {
    actions: 'ድርጊቶች',
    active: 'ንቁ',
    allModels: 'ሁሉም ሞዴሎች',
    allStatuses: 'ሁሉም ሁኔታዎች',
    allTokens: 'ሁሉም ቶከኖች',
    apply: 'ተግብር',
    availableModels: 'የሚገኙ ሞዴሎች',
    balance: 'ቀሪ ሂሳብ',
    billing: 'ክፍያ',
    cancel: 'ሰርዝ',
    copy: 'ቅዳ',
    delete: 'አጥፋ',
    edit: 'አርትዕ',
    error: 'ስህተት',
    event: 'ክስተት',
    failed: 'አልተሳካም',
    filters: 'ማጣሪያዎች',
    input: 'ግቤት',
    model: 'ሞዴል',
    name: 'ስም',
    output: 'ውጤት',
    quota: 'ገደብ',
    rechargeCode: 'የመሙያ ኮድ',
    records: 'መዝገቦች',
    save: 'አስቀምጥ',
    search: 'ፈልግ',
    select: 'ምረጥ',
    send: 'ላክ',
    status: 'ሁኔታ',
    time: 'ጊዜ',
    timezone: 'የጊዜ ቀጠና'
  },
  'ha-NG': {
    actions: 'Ayyuka',
    active: 'Yana aiki',
    allModels: 'Duk samfura',
    allStatuses: 'Duk matsayi',
    allTokens: 'Duk token',
    apply: 'Aiwatar',
    availableModels: 'Samfura da ake samu',
    balance: "Ma'auni",
    billing: 'Lissafi',
    cancel: 'Soke',
    copy: 'Kwafa',
    delete: 'Share',
    edit: 'Gyara',
    error: 'Kuskure',
    event: 'Lamari',
    failed: 'Ya gaza',
    filters: 'Matattara',
    input: 'Shigarwa',
    model: 'Samfuri',
    name: 'Suna',
    output: 'Fitarwa',
    quota: 'Kaso',
    rechargeCode: 'Lambar caji',
    records: 'Rubuce-rubuce',
    save: 'Ajiye',
    search: 'Bincika',
    select: 'Zaba',
    send: 'Aika',
    status: 'Matsayi',
    time: 'Lokaci',
    timezone: 'Yankin lokaci'
  },
  'yo-NG': {
    actions: 'Awọn iṣe',
    active: 'Nṣiṣẹ',
    allModels: 'Gbogbo awoṣe',
    allStatuses: 'Gbogbo ipo',
    allTokens: 'Gbogbo tokeni',
    apply: 'Lo',
    availableModels: 'Awọn awoṣe to wa',
    balance: 'Iwontunwonsi',
    billing: 'Idiyele',
    cancel: 'Fagilee',
    copy: 'Daakọ',
    delete: 'Paarẹ',
    edit: 'Ṣatunkọ',
    error: 'Aṣiṣe',
    event: 'Iṣẹlẹ',
    failed: 'Kuna',
    filters: 'Ajọ',
    input: 'Iwọle',
    model: 'Awoṣe',
    name: 'Orukọ',
    output: 'Abajade',
    quota: 'Ipin',
    rechargeCode: 'Koodu gbigba agbara',
    records: 'Awọn igbasilẹ',
    save: 'Fipamọ',
    search: 'Wa',
    select: 'Yan',
    send: 'Firanṣẹ',
    status: 'Ipo',
    time: 'Akoko',
    timezone: 'Agbegbe akoko'
  },
  'ig-NG': {
    actions: 'Omume',
    active: 'Na-arụ ọrụ',
    allModels: 'Ụdị niile',
    allStatuses: 'Ọnọdụ niile',
    allTokens: 'Token niile',
    apply: 'Tinye',
    availableModels: 'Ụdị dị',
    balance: 'Ntụle ego',
    billing: 'Ịgba ụgwọ',
    cancel: 'Kagbuo',
    copy: 'Detuo',
    delete: 'Hichapụ',
    edit: 'Dezie',
    error: 'Njehie',
    event: 'Ihe omume',
    failed: 'Dara',
    filters: 'Nzacha',
    input: 'Ntinye',
    model: 'Ụdị',
    name: 'Aha',
    output: 'Mmepụta',
    quota: 'Oke',
    rechargeCode: 'Koodu itinye ego',
    records: 'Ndekọ',
    save: 'Chekwaa',
    search: 'Chọọ',
    select: 'Họrọ',
    send: 'Zipu',
    status: 'Ọnọdụ',
    time: 'Oge',
    timezone: 'Mpaghara oge'
  },
  'zu-ZA': {
    actions: 'Izenzo',
    active: 'Iyasebenza',
    allModels: 'Wonke amamodeli',
    allStatuses: 'Zonke izimo',
    allTokens: 'Wonke amathokheni',
    apply: 'Sebenzisa',
    availableModels: 'Amamodeli atholakalayo',
    balance: 'Ibhalansi',
    billing: 'Ukukhokhisa',
    cancel: 'Khansela',
    copy: 'Kopisha',
    delete: 'Susa',
    edit: 'Hlela',
    error: 'Iphutha',
    event: 'Umcimbi',
    failed: 'Kwehlulekile',
    filters: 'Izihlungi',
    input: 'Okokufaka',
    model: 'Imodeli',
    name: 'Igama',
    output: 'Okuphumayo',
    quota: 'Umkhawulo',
    rechargeCode: 'Ikhodi yokugcwalisa',
    records: 'Amarekhodi',
    save: 'Londoloza',
    search: 'Sesha',
    select: 'Khetha',
    send: 'Thumela',
    status: 'Isimo',
    time: 'Isikhathi',
    timezone: 'Indawo yesikhathi'
  },
  'af-ZA': {
    actions: 'Aksies',
    active: 'Aktief',
    allModels: 'Alle modelle',
    allStatuses: 'Alle statusse',
    allTokens: 'Alle tokens',
    apply: 'Pas toe',
    availableModels: 'Beskikbare modelle',
    balance: 'Saldo',
    billing: 'Fakturering',
    cancel: 'Kanselleer',
    copy: 'Kopieer',
    delete: 'Verwyder',
    edit: 'Wysig',
    error: 'Fout',
    event: 'Gebeurtenis',
    failed: 'Misluk',
    filters: 'Filters',
    input: 'Invoer',
    model: 'Model',
    name: 'Naam',
    output: 'Uitvoer',
    quota: 'Kwota',
    rechargeCode: 'Herlaaikode',
    records: 'Rekords',
    save: 'Stoor',
    search: 'Soek',
    select: 'Kies',
    send: 'Stuur',
    status: 'Status',
    time: 'Tyd',
    timezone: 'Tydsone'
  },
  'so-SO': {
    actions: 'Ficillo',
    active: 'Firfircoon',
    allModels: 'Dhammaan moodallada',
    allStatuses: 'Dhammaan xaaladaha',
    allTokens: 'Dhammaan tokennada',
    apply: 'Codso',
    availableModels: 'Moodallo la heli karo',
    balance: 'Hadhaaga',
    billing: 'Biil',
    cancel: 'Jooji',
    copy: 'Nuqul',
    delete: 'Tirtir',
    edit: 'Tafatir',
    error: 'Khalad',
    event: 'Dhacdo',
    failed: 'Fashilmay',
    filters: 'Shaandheeyayaal',
    input: 'Gelin',
    model: 'Moodal',
    name: 'Magac',
    output: 'Soo saar',
    quota: 'Xad',
    rechargeCode: 'Koodhka buuxinta',
    records: 'Diiwaanno',
    save: 'Kaydi',
    search: 'Raadi',
    select: 'Dooro',
    send: 'Dir',
    status: 'Xaalad',
    time: 'Waqti',
    timezone: 'Aagga waqtiga'
  },
  'rw-RW': {
    actions: 'Ibikorwa',
    active: 'Birakora',
    allModels: 'Moderi zose',
    allStatuses: 'Imimerere yose',
    allTokens: 'Tokene zose',
    apply: 'Emeza',
    availableModels: 'Moderi ziboneka',
    balance: 'Amafaranga asigaye',
    billing: 'Kwishyura',
    cancel: 'Hagarika',
    copy: 'Koporora',
    delete: 'Siba',
    edit: 'Hindura',
    error: 'Ikosa',
    event: 'Icyabaye',
    failed: 'Byanze',
    filters: 'Muyunguruzi',
    input: 'Iyinjiza',
    model: 'Moderi',
    name: 'Izina',
    output: 'Ibisohoka',
    quota: 'Igipimo',
    rechargeCode: 'Kode yo kongera konti',
    records: 'Inyandiko',
    save: 'Bika',
    search: 'Shaka',
    select: 'Hitamo',
    send: 'Ohereza',
    status: 'Imimerere',
    time: 'Igihe',
    timezone: "Agace k'igihe"
  },
  'om-ET': {
    actions: 'Gochota',
    active: 'Hojii irra jira',
    allModels: 'Moodeelota hunda',
    allStatuses: 'Haalota hunda',
    allTokens: 'Tokenota hunda',
    apply: 'Fayyadami',
    availableModels: 'Moodeelota argaman',
    balance: 'Haftee',
    billing: 'Kaffaltii',
    cancel: 'Dhiisi',
    copy: 'Garagalchi',
    delete: 'Haquu',
    edit: 'Gulaali',
    error: 'Dogoggora',
    event: 'Taatee',
    failed: 'Hin milkoofne',
    filters: 'Calaltuu',
    input: 'Galtee',
    model: 'Moodeela',
    name: 'Maqaa',
    output: "Bu'aa",
    quota: 'Daangaa',
    rechargeCode: 'Koodii guutuu',
    records: 'Galmee',
    save: "Olkaa'i",
    search: 'Barbaadi',
    select: 'Filadhu',
    send: 'Ergi',
    status: 'Haala',
    time: 'Yeroo',
    timezone: 'Naannoo yeroo'
  },
  'hi-IN': {
    actions: 'कार्रवाइयां',
    active: 'सक्रिय',
    allModels: 'सभी मॉडल',
    allStatuses: 'सभी स्थितियां',
    allTokens: 'सभी टोकन',
    apply: 'लागू करें',
    availableModels: 'उपलब्ध मॉडल',
    balance: 'शेष राशि',
    billing: 'बिलिंग',
    cancel: 'रद्द करें',
    copy: 'कॉपी',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    error: 'त्रुटि',
    event: 'घटना',
    expiresAt: 'समाप्ति',
    failed: 'विफल',
    filters: 'फिल्टर',
    input: 'इनपुट',
    model: 'मॉडल',
    name: 'नाम',
    output: 'आउटपुट',
    quota: 'कोटा',
    rechargeCode: 'रिचार्ज कोड',
    records: 'रिकॉर्ड',
    save: 'सहेजें',
    search: 'खोजें',
    select: 'चुनें',
    send: 'भेजें',
    status: 'स्थिति',
    time: 'समय',
    timezone: 'समय क्षेत्र'
  },
  'id-ID': {
    actions: 'Tindakan',
    active: 'Aktif',
    allModels: 'Semua model',
    allStatuses: 'Semua status',
    allTokens: 'Semua token',
    apply: 'Terapkan',
    availableModels: 'Model tersedia',
    balance: 'Saldo',
    billing: 'Penagihan',
    cancel: 'Batal',
    copy: 'Salin',
    delete: 'Hapus',
    edit: 'Edit',
    error: 'Kesalahan',
    event: 'Peristiwa',
    failed: 'Gagal',
    filters: 'Filter',
    input: 'Input',
    model: 'Model',
    name: 'Nama',
    output: 'Output',
    quota: 'Kuota',
    rechargeCode: 'Kode isi ulang',
    records: 'Catatan',
    save: 'Simpan',
    search: 'Cari',
    select: 'Pilih',
    send: 'Kirim',
    status: 'Status',
    time: 'Waktu',
    timezone: 'Zona waktu'
  },
  'tr-TR': {
    actions: 'İşlemler',
    active: 'Aktif',
    allModels: 'Tüm modeller',
    allStatuses: 'Tüm durumlar',
    allTokens: 'Tüm tokenlar',
    apply: 'Uygula',
    availableModels: 'Kullanılabilir modeller',
    balance: 'Bakiye',
    billing: 'Faturalama',
    cancel: 'İptal',
    copy: 'Kopyala',
    delete: 'Sil',
    edit: 'Düzenle',
    error: 'Hata',
    event: 'Olay',
    failed: 'Başarısız',
    filters: 'Filtreler',
    input: 'Girdi',
    model: 'Model',
    name: 'Ad',
    output: 'Çıktı',
    quota: 'Kota',
    rechargeCode: 'Yukleme kodu',
    records: 'Kayıtlar',
    save: 'Kaydet',
    search: 'Ara',
    select: 'Seç',
    send: 'Gönder',
    status: 'Durum',
    time: 'Zaman',
    timezone: 'Saat dilimi'
  },
  'vi-VN': {
    actions: 'Hành động',
    active: 'Hoạt động',
    allModels: 'Tất cả mô hình',
    allStatuses: 'Tất cả trạng thái',
    allTokens: 'Tất cả token',
    apply: 'Áp dụng',
    availableModels: 'Mô hình khả dụng',
    balance: 'Số dư',
    billing: 'Thanh toán',
    cancel: 'Hủy',
    copy: 'Sao chép',
    delete: 'Xóa',
    edit: 'Sửa',
    error: 'Lỗi',
    event: 'Sự kiện',
    failed: 'Thất bại',
    filters: 'Bộ lọc',
    input: 'Đầu vào',
    model: 'Mô hình',
    name: 'Tên',
    output: 'Đầu ra',
    quota: 'Hạn mức',
    rechargeCode: 'Ma nap tien',
    records: 'Bản ghi',
    save: 'Lưu',
    search: 'Tìm kiếm',
    select: 'Chọn',
    send: 'Gửi',
    status: 'Trạng thái',
    time: 'Thời gian',
    timezone: 'Múi giờ'
  },
  'th-TH': {
    actions: 'การดำเนินการ',
    active: 'ใช้งานอยู่',
    allModels: 'โมเดลทั้งหมด',
    allStatuses: 'สถานะทั้งหมด',
    allTokens: 'โทเคนทั้งหมด',
    apply: 'ใช้',
    availableModels: 'โมเดลที่ใช้ได้',
    balance: 'ยอดคงเหลือ',
    billing: 'การเรียกเก็บเงิน',
    cancel: 'ยกเลิก',
    copy: 'คัดลอก',
    delete: 'ลบ',
    edit: 'แก้ไข',
    error: 'ข้อผิดพลาด',
    event: 'เหตุการณ์',
    failed: 'ล้มเหลว',
    filters: 'ตัวกรอง',
    input: 'อินพุต',
    model: 'โมเดล',
    name: 'ชื่อ',
    output: 'เอาต์พุต',
    quota: 'โควตา',
    rechargeCode: 'รหัสเติมเงิน',
    records: 'ระเบียน',
    save: 'บันทึก',
    search: 'ค้นหา',
    select: 'เลือก',
    send: 'ส่ง',
    status: 'สถานะ',
    time: 'เวลา',
    timezone: 'เขตเวลา'
  },
  'it-IT': {
    actions: 'Azioni',
    active: 'Attivo',
    allModels: 'Tutti i modelli',
    allStatuses: 'Tutti gli stati',
    allTokens: 'Tutti i token',
    apply: 'Applica',
    availableModels: 'Modelli disponibili',
    balance: 'Saldo',
    billing: 'Fatturazione',
    cancel: 'Annulla',
    copy: 'Copia',
    delete: 'Elimina',
    edit: 'Modifica',
    error: 'Errore',
    event: 'Evento',
    failed: 'Non riuscito',
    filters: 'Filtri',
    input: 'Input',
    model: 'Modello',
    name: 'Nome',
    output: 'Output',
    quota: 'Quota',
    rechargeCode: 'Codice di ricarica',
    records: 'Record',
    save: 'Salva',
    search: 'Cerca',
    select: 'Seleziona',
    send: 'Invia',
    status: 'Stato',
    time: 'Ora',
    timezone: 'Fuso orario'
  },
  'nl-NL': {
    actions: 'Acties',
    active: 'Actief',
    allModels: 'Alle modellen',
    allStatuses: 'Alle statussen',
    allTokens: 'Alle tokens',
    apply: 'Toepassen',
    availableModels: 'Beschikbare modellen',
    balance: 'Saldo',
    billing: 'Facturering',
    cancel: 'Annuleren',
    copy: 'Kopieren',
    delete: 'Verwijderen',
    edit: 'Bewerken',
    error: 'Fout',
    event: 'Gebeurtenis',
    failed: 'Mislukt',
    filters: 'Filters',
    input: 'Invoer',
    model: 'Model',
    name: 'Naam',
    output: 'Uitvoer',
    quota: 'Quotum',
    rechargeCode: 'Opwaardeercode',
    records: 'Records',
    save: 'Opslaan',
    search: 'Zoeken',
    select: 'Selecteren',
    send: 'Verzenden',
    status: 'Status',
    time: 'Tijd',
    timezone: 'Tijdzone'
  },
  'pl-PL': {
    actions: 'Akcje',
    active: 'Aktywne',
    allModels: 'Wszystkie modele',
    allStatuses: 'Wszystkie statusy',
    allTokens: 'Wszystkie tokeny',
    apply: 'Zastosuj',
    availableModels: 'Dostępne modele',
    balance: 'Saldo',
    billing: 'Rozliczenia',
    cancel: 'Anuluj',
    copy: 'Kopiuj',
    delete: 'Usuń',
    edit: 'Edytuj',
    error: 'Błąd',
    event: 'Zdarzenie',
    failed: 'Niepowodzenie',
    filters: 'Filtry',
    input: 'Wejście',
    model: 'Model',
    name: 'Nazwa',
    output: 'Wyjście',
    quota: 'Limit',
    rechargeCode: 'Kod doladowania',
    records: 'Rekordy',
    save: 'Zapisz',
    search: 'Szukaj',
    select: 'Wybierz',
    send: 'Wyślij',
    status: 'Status',
    time: 'Czas',
    timezone: 'Strefa czasowa'
  },
  'uk-UA': {
    actions: 'Дії',
    active: 'Активно',
    allModels: 'Усі моделі',
    allStatuses: 'Усі статуси',
    allTokens: 'Усі токени',
    apply: 'Застосувати',
    availableModels: 'Доступні моделі',
    balance: 'Баланс',
    billing: 'Білінг',
    cancel: 'Скасувати',
    copy: 'Копіювати',
    delete: 'Видалити',
    edit: 'Редагувати',
    error: 'Помилка',
    event: 'Подія',
    failed: 'Не вдалося',
    filters: 'Фільтри',
    input: 'Ввід',
    model: 'Модель',
    name: 'Назва',
    output: 'Вивід',
    quota: 'Квота',
    rechargeCode: 'Код поповнення',
    records: 'Записи',
    save: 'Зберегти',
    search: 'Пошук',
    select: 'Вибрати',
    send: 'Надіслати',
    status: 'Статус',
    time: 'Час',
    timezone: 'Часовий пояс'
  },
  'ms-MY': {
    actions: 'Tindakan',
    active: 'Aktif',
    allModels: 'Semua model',
    allStatuses: 'Semua status',
    allTokens: 'Semua token',
    apply: 'Guna',
    availableModels: 'Model tersedia',
    balance: 'Baki',
    billing: 'Pengebilan',
    cancel: 'Batal',
    copy: 'Salin',
    delete: 'Padam',
    edit: 'Edit',
    error: 'Ralat',
    event: 'Peristiwa',
    failed: 'Gagal',
    filters: 'Penapis',
    input: 'Input',
    model: 'Model',
    name: 'Nama',
    output: 'Output',
    quota: 'Kuota',
    rechargeCode: 'Kod tambah nilai',
    records: 'Rekod',
    save: 'Simpan',
    search: 'Cari',
    select: 'Pilih',
    send: 'Hantar',
    status: 'Status',
    time: 'Masa',
    timezone: 'Zon masa'
  },
  'fa-IR': {
    actions: 'عملیات',
    active: 'فعال',
    allModels: 'همه مدل‌ها',
    allStatuses: 'همه وضعیت‌ها',
    allTokens: 'همه توکن‌ها',
    apply: 'اعمال',
    availableModels: 'مدل‌های در دسترس',
    balance: 'موجودی',
    billing: 'صورتحساب',
    cancel: 'لغو',
    copy: 'کپی',
    delete: 'حذف',
    edit: 'ویرایش',
    error: 'خطا',
    event: 'رویداد',
    failed: 'ناموفق',
    filters: 'فیلترها',
    input: 'ورودی',
    model: 'مدل',
    name: 'نام',
    output: 'خروجی',
    quota: 'سهمیه',
    rechargeCode: 'کد شارژ',
    records: 'رکوردها',
    save: 'ذخیره',
    search: 'جستجو',
    select: 'انتخاب',
    send: 'ارسال',
    status: 'وضعیت',
    time: 'زمان',
    timezone: 'منطقه زمانی'
  }
};

const FALLBACK_TERM_ALIASES: Partial<Record<PageTermKey, PageTermKey>> = {
  allTokens: 'token',
  allUsableModels: 'availableModels',
  calls: 'records',
  charged: 'billing',
  configured: 'active',
  cost: 'billing',
  copyAllModels: 'availableModels',
  copyModelName: 'model',
  createToken: 'token',
  createdAt: 'time',
  currentUser: 'user',
  currentPassword: 'password',
  deleteSelected: 'delete',
  deleted: 'delete',
  deliveryRecords: 'records',
  disabled: 'failed',
  editToken: 'token',
  emptyLogs: 'records',
  emptyModels: 'model',
  emptyRecords: 'records',
  emptyTokens: 'token',
  enabled: 'active',
  eventSubscriptions: 'event',
  expired: 'failed',
  expiresAt: 'time',
  export: 'copy',
  failedCalls: 'failed',
  filteredCharges: 'billing',
  free: 'billing',
  lastLogin: 'time',
  lastLoginIp: 'time',
  lastUsed: 'time',
  leaderboard: 'totalTokens',
  lowBalanceAlert: 'balance',
  mergedChargeTotal: 'billing',
  modelConfig: 'model',
  modelDistribution: 'model',
  modelList: 'model',
  modelPriceUpdates: 'model',
  modelSearch: 'search',
  neverExpires: 'expiresAt',
  newPassword: 'password',
  nextPage: 'records',
  noCopyModels: 'model',
  noData: 'records',
  noLimit: 'quota',
  notConfigured: 'failed',
  notEnabled: 'failed',
  note: 'records',
  notificationChannels: 'notificationSettings',
  previousPage: 'records',
  promotions: 'event',
  rank: 'records',
  remainingQuota: 'quota',
  reset: 'apply',
  resetKey: 'token',
  saveSettings: 'save',
  saving: 'save',
  securityAlerts: 'event',
  sent: 'send',
  systemAnnouncements: 'event',
  systemToken: 'token',
  target: 'name',
  test: 'apply',
  testing: 'loading',
  threshold: 'quota',
  timeRange: 'time',
  totalSpend: 'balance',
  totalTokens: 'token',
  unknownMetering: 'billing',
  upstreamTokens: 'token',
  usageDetails: 'records',
  visibleRows: 'records'
};

const LANGUAGE_NEUTRAL_TERMS = new Set<PageTermKey>(['webhook']);

function lookupLocalTerm(language: LanguageCode, key: PageTermKey) {
  const translationKey = TRANSLATION_KEYS[key];
  if (translationKey) {
    return translate(language, translationKey);
  }

  return EXTRA_LOCAL_TERMS[language]?.[key] ?? LOCAL_TERMS[language]?.[key];
}

function lookupAliasedLocalTerm(language: LanguageCode, key: PageTermKey) {
  const visited = new Set<PageTermKey>();
  let current: PageTermKey | undefined = key;

  while (current) {
    if (visited.has(current)) {
      return undefined;
    }

    visited.add(current);
    const localized = lookupLocalTerm(language, current);
    if (localized) {
      return localized;
    }

    current = FALLBACK_TERM_ALIASES[current];
  }

  return undefined;
}

export function pageTerm(language: LanguageCode, key: PageTermKey) {
  const localized = lookupAliasedLocalTerm(language, key);
  if (localized) {
    return localized;
  }

  const english = ENGLISH_TERMS[key];
  if (language === 'en-US' || LANGUAGE_NEUTRAL_TERMS.has(key)) {
    return english;
  }

  return `${getLanguageLabel(language)} ${english}`;
}

export function pageRows(language: LanguageCode, count: number) {
  return `${count} ${pageTerm(language, 'visibleRows')}`;
}
